name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test_valid:
    name: Test valid messages
    runs-on: "ubuntu-latest"
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Message should be successful"
        uses: "./"
        with:
          title: "feat: testing funny things"

  test_invalid:
    name: Test invalid messages
    runs-on: "ubuntu-latest"
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # check that the action outputs `valid` set to `false` when invalid message is provided
      - name: "Message should not be successful"
        id: invalid_message
        uses: "./"
        with:
          title: "invalid title"
          fail-on-error: false

      - name: Check for action output
        run: |
          echo $FAILURE
          if [ "${{ steps.invalid_message.outputs.valid }}" = "false" ]; then
            echo "Action doesn't output `valid=false`"
            exit 0
          else
            exit 1
          fi

  format:
    name: "Check format"
    runs-on: "ubuntu-latest"
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js (via input)
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Check format
        run: pnpm run format
